version: "2.0"

services:
  ml:
    image: nvidia/cuda:12.0-runtime-ubuntu22.04
    command:
      - "nvidia-smi"
      - "-l"
      - "60"
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    ml:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          size: 50Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:

  placement:
    dcloud:
      pricing:
        ml:
          denom: uact
          amount: 10000

deployment:
  ml:
    dcloud:
      profile: ml
      count: 1
